version: '3.8'

services:

  db:
    image: postgres:16.0-alpine
    env_file: .env.docker
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      IN_DOCKER: "True"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    env_file: .env.docker
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      IN_DOCKER: "True"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./collected_static:/code/collected_static
      - ./media:/code/media
    ports:
      - "8000:8000"
    command: sh -c "
        echo 'Ожидание БД...' &&
        until pg_isready -h db -U $${DB_USER} -d $${DB_NAME}; do
          sleep 2;
        done &&
        python manage.py collectstatic --noinput &&
        python manage.py migrate &&
        python manage.py fill_db_content &&
        python manage.py fill_db &&
        python manage.py runserver 0.0.0.0:8000
      "
    restart: unless-stopped

volumes:
  postgres_data:
