# Generated by Django 6.0.3 on 2026-03-16 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="название")),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="порядок отображения"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активна"),
                ),
            ],
            options={
                "verbose_name": "категория услуги",
                "verbose_name_plural": "категории услуг",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Запланировано на"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments_as_doctor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Врач",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись на приём",
                "verbose_name_plural": "Записи на приём",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DiagnosisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="файл с результатами диагностики",
                        upload_to="diagnosis_results/",
                        verbose_name="Файл с результатами",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "В обработке"),
                            ("completed", "Готово"),
                            ("failed", "Ошибка"),
                        ],
                        default="processing",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительные комментарии к результатам",
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnosis_results",
                        to="services.appointment",
                        verbose_name="Запись на приём",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат диагностики",
                "verbose_name_plural": "Результаты диагностики",
                "ordering": ["-uploaded_at"],
            },
        ),

        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="название")),
                ("description", models.TextField(verbose_name="описание")),
                (
                    "short_description",
                    models.TextField(max_length=500, verbose_name="краткое описание"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="цена"
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=30, verbose_name="длительность (минут)"
                    ),
                ),
                (
                    "preparation",
                    models.TextField(
                        blank=True,
                        help_text="Инструкции по подготовке к диагностической процедуре",
                        verbose_name="подготовка к процедуре",
                    ),
                ),
                (
                    "results_time",
                    models.CharField(
                        blank=True,
                        help_text='Например: "через 1-2 дня", "в течение часа" и т.д.',
                        max_length=100,
                        verbose_name="время получения результатов",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="порядок отображения"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="дата обновления"),
                ),
                (
                    "doctors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="services_as_doctor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Врачи",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="services.servicecategory",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "медицинская услуга",
                "verbose_name_plural": "медицинские услуги",
                "ordering": ["category", "name"],
            },
        ),
        migrations.AddField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="services.service",
                verbose_name="Услуга",
            ),
        ),
        migrations.CreateModel(
            name="ServiceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="service_images/", verbose_name="изображение"
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        default=False,
                        help_text="Отметьте, если это основное изображение для категории услуги",
                        verbose_name="основное изображение",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="порядок отображения"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="services.servicecategory",
                        verbose_name="категория услуги",
                    ),
                ),
            ],
            options={
                "verbose_name": "изображение категории услуги",
                "verbose_name_plural": "изображения категорий услуг",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="DoctorSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Понедельник"),
                            (1, "Вторник"),
                            (2, "Среда"),
                            (3, "Четверг"),
                            (4, "Пятница"),
                            (5, "Суббота"),
                            (6, "Воскресенье"),
                        ],
                        verbose_name="День недели",
                    ),
                ),
                (
                    "time_of_day",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "09:00"),
                            (1, "09:30"),
                            (2, "10:00"),
                            (3, "10:30"),
                            (4, "11:00"),
                            (5, "11:30"),
                            (6, "12:00"),
                            (7, "12:30"),
                            (8, "13:00"),
                            (9, "13:30"),
                            (10, "14:00"),
                            (11, "14:30"),
                            (12, "15:00"),
                            (13, "15:30"),
                            (14, "16:00"),
                            (15, "16:30"),
                            (16, "17:00"),
                        ],
                        verbose_name="Часы приема",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Врач",
                    ),
                ),
            ],
            options={
                "verbose_name": "График работы врача",
                "verbose_name_plural": "Графики работы врачей",
                "ordering": ["day_of_week", "time_of_day"],
                "unique_together": {("doctor", "day_of_week", "time_of_day")},
            },
        ),
    ]
