# Generated by Django 6.0.3 on 2026-03-07 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
            ],
            options={
                'verbose_name': 'категория услуги',
                'verbose_name_plural': 'категории услуг',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('short_description', models.TextField(max_length=500, verbose_name='краткое описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('duration', models.PositiveIntegerField(default=30, verbose_name='длительность (минут)')),
                ('preparation', models.TextField(blank=True, help_text='Инструкции по подготовке к диагностической процедуре', verbose_name='подготовка к процедуре')),
                ('results_time', models.CharField(blank=True, help_text='Например: "через 1-2 дня", "в течение часа" и т.д.', max_length=100, verbose_name='время получения результатов')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'медицинская услуга',
                'verbose_name_plural': 'медицинские услуги',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_images/', verbose_name='изображение')),
                ('is_main', models.BooleanField(default=False, help_text='Отметьте, если это основное изображение для услуги', verbose_name='основное изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок отображения')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service', verbose_name='услуга')),
            ],
            options={
                'verbose_name': 'изображение услуги',
                'verbose_name_plural': 'изображения услуг',
                'ordering': ['order'],
            },
        ),
    ]
