# Generated by Django 6.0.3 on 2026-03-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecategory",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="service_category_images/",
                verbose_name="изображение",
            ),
        ),
        migrations.DeleteModel(
            name="ServiceImage",
        ),
    ]
