# Generated by Django 6.0.3 on 2026-03-13 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['category', 'name'], 'verbose_name': 'медицинская услуга', 'verbose_name_plural': 'медицинские услуги'},
        ),
        migrations.AlterModelOptions(
            name='serviceimage',
            options={'ordering': ['order'], 'verbose_name': 'изображение категории услуги', 'verbose_name_plural': 'изображения категорий услуг'},
        ),
        migrations.RemoveField(
            model_name='serviceimage',
            name='service',
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.servicecategory', verbose_name='категория услуги'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Отметьте, если это основное изображение для категории услуги', verbose_name='основное изображение'),
        ),
    ]
