# Generated by Django 6.0.3 on 2026-03-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="user_images/", verbose_name="Фото"
            ),
        ),
    ]
