# Generated by Django 6.0.3 on 2026-03-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="Адрес"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="Дата рождения"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Почта"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Номер телефона"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=30, unique=True, verbose_name="Имя пользователя"
            ),
        ),
    ]
