# Generated by Django 6.0.3 on 2026-03-19 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fragment",
            options={
                "ordering": ["-title"],
                "verbose_name": "Фрагмент",
                "verbose_name_plural": "Фрагменты",
            },
        ),
    ]
